default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false

MazeBrainTest:
    max_steps: 5.0e4
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 64
    num_layers: 2
    
MazeBrain:
    use_recurrent: true
    sequence_length: 64
    memory_size: 256
    num_layers: 2
    gamma: 0.99
    batch_size: 128
    buffer_size: 2048
    num_epoch: 5
    learning_rate: 3.0e-4
    time_horizon: 64
    max_steps: 5e4
    beta: 5e-3
    epsilon: 0.2
    normalize: false
    hidden_units: 512
    
    
    